[package]
name = "embedded-websocket"
version = "0.9.7"
authors = ["David Haig"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ninjasource/embedded-websockets.git"
description = "A lightweight websocket library for embedded systems (no_std)"
keywords = ["websockets", "websocket", "embedded", "no_std"]
categories = ["embedded", "no-std", "network-programming"]
readme = "README.md"

[dependencies]
sha1 = { version = "0.11.0", default-features = false }
heapless = { version = "0.9.3", default-features = false }
byteorder = { version = "1.5.0", default-features = false }
httparse = { version = "1.10.1", default-features = false }
rand_core = { version = "0.10.1", default-features = false }
base64 = { version = "0.23.1", default-features = false }
futures = { version = "0.3.31", default-features = false }
embedded-io-async = { version = "0.7.0", default-features = false, optional = true }

[dev-dependencies]
rand = "0.10.2"
bytes = "1.9.0"
tokio = { version = "1.53.1", features = [
    "macros",
    "rt-multi-thread",
    "io-util",
] }
tokio-util = { version = "0.7.19", features = ["net", "codec"] }
embedded-io-adapters = { version = "0.7.0", features = ["tokio-1"] }

# see readme for no_std support
[features]
default = ["std"]
# default = []
std = ["httparse/std"]
embedded-io-async = ["dep:embedded-io-async"]


[[example]]
name = "client_async_embedded_io_async"
path = "examples/client_async_embedded_io_async.rs"
required-features = ["embedded-io-async"]

[[example]]
name = "server_async"
path = "examples/server_async.rs"
# required-features = ["std"]
